import 'package:demo_app/app/data/models/models.dart';
import 'package:flutter/material.dart';

// Static list of tabs with icons
final List<TabModel> tabs = [
  TabModel(
    title: "Personal",
    order: 1,
    isPermanent: true,
    tabType: TabType.form,
    icon: Icons.person,
    sections: [
      SectionModel(
        title: "Basic Information",
        order: 1,
        isPermanent: true,
        icon: Icons.info,
        fields: [
          FieldModel(
            label: "Employee #",
            hint: "Enter employee number",
            dataType: FieldDataType.text,
            value: null,
            validations: {"required": true},
            options: null,
            allowMultiple: false,
            isPermanent: true,
          ),
          FieldModel(
            label: "Status",
            hint: "Select status",
            dataType: FieldDataType.dropdown,
            value: null,
            validations: {"required": true},
            options: ["Active", "Inactive", "On Leave", "Terminated"],
            allowMultiple: false,
            isPermanent: true,
          ),
          FieldModel(
            label: "First Name",
            hint: "Enter first name",
            dataType: FieldDataType.text,
            value: null,
            validations: {"required": true},
            options: null,
            allowMultiple: false,
            isPermanent: true,
          ),
          FieldModel(
            label: "Middle Name",
            hint: "Enter middle name",
            dataType: FieldDataType.text,
            value: null,
            validations: {},
            options: null,
            allowMultiple: false,
            isPermanent: false,
          ),
          FieldModel(
            label: "Last Name",
            hint: "Enter last name",
            dataType: FieldDataType.text,
            value: null,
            validations: {"required": true},
            options: null,
            allowMultiple: false,
            isPermanent: true,
          ),
          FieldModel(
            label: "Preferred Name",
            hint: "Enter preferred name",
            dataType: FieldDataType.text,
            value: null,
            validations: {},
            options: null,
            allowMultiple: false,
            isPermanent: false,
          ),
          FieldModel(
            label: "Birth Date",
            hint: "mm/dd/yyyy",
            dataType: FieldDataType.date,
            value: null,
            validations: {"required": true},
            options: null,
            allowMultiple: false,
            isPermanent: true,
          ),
          FieldModel(
            label: "Age",
            hint: "Enter age",
            dataType: FieldDataType.number,
            value: null,
            validations: {},
            options: null,
            allowMultiple: false,
            isPermanent: false,
          ),
          FieldModel(
            label: "Gender",
            hint: "Select gender",
            dataType: FieldDataType.dropdown,
            value: null,
            validations: {"required": true},
            options: ["Male", "Female", "Other", "Prefer not to say"],
            allowMultiple: false,
            isPermanent: true,
          ),
          FieldModel(
            label: "Marital Status",
            hint: "Select marital status",
            dataType: FieldDataType.dropdown,
            value: null,
            validations: {"required": true},
            options: ["Single", "Married", "Divorced", "Widowed", "Separated"],
            allowMultiple: false,
            isPermanent: true,
          ),
          FieldModel(
            label: "SSN",
            hint: "Enter SSN",
            dataType: FieldDataType.text,
            value: null,
            validations: {},
            options: null,
            allowMultiple: false,
            isPermanent: false,
          ),
          FieldModel(
            label: "Tax File Number",
            hint: "Enter tax file number",
            dataType: FieldDataType.text,
            value: null,
            validations: {},
            options: null,
            allowMultiple: false,
            isPermanent: false,
          ),
          FieldModel(
            label: "NN",
            hint: "Enter NN",
            dataType: FieldDataType.text,
            value: null,
            validations: {},
            options: null,
            allowMultiple: false,
            isPermanent: false,
          ),
          FieldModel(
            label: "Shirt Size",
            hint: "Select shirt size",
            dataType: FieldDataType.dropdown,
            value: null,
            validations: {},
            options: ["XS", "S", "M", "L", "XL", "XXL", "XXXL"],
            allowMultiple: false,
            isPermanent: false,
          ),
          FieldModel(
            label: "Allergies",
            hint: "List any allergies",
            dataType: FieldDataType.text,
            value: null,
            validations: {},
            options: null,
            allowMultiple: true,
            isPermanent: false,
          ),
          FieldModel(
            label: "Dietary Restrictions",
            hint: "Select dietary restrictions",
            dataType: FieldDataType.dropdown,
            value: null,
            validations: {},
            options: [
              "None",
              "Vegetarian",
              "Vegan",
              "Gluten-Free",
              "Dairy-Free",
              "Kosher",
              "Halal",
              "Other"
            ],
            allowMultiple: true,
            isPermanent: false,
          ),
        ],
      ),
      SectionModel(
        title: "Address",
        order: 2,
        isPermanent: true,
        icon: Icons.home,
        fields: [
          FieldModel(
            label: "Street",
            hint: "123 Main St",
            dataType: FieldDataType.text,
            value: null,
            validations: {"required": true},
            options: null,
            allowMultiple: false,
            isPermanent: true,
          ),
          FieldModel(
            label: "City",
            hint: "Enter city",
            dataType: FieldDataType.text,
            value: null,
            validations: {"required": true},
            options: null,
            allowMultiple: false,
            isPermanent: true,
          ),
          FieldModel(
            label: "State/Province",
            hint: "Enter state/province",
            dataType: FieldDataType.text,
            value: null,
            validations: {"required": true},
            options: null,
            allowMultiple: false,
            isPermanent: true,
          ),
          FieldModel(
            label: "ZIP/Postal code",
            hint: "Enter ZIP/postal code",
            dataType: FieldDataType.text,
            value: null,
            validations: {"required": true},
            options: null,
            allowMultiple: false,
            isPermanent: true,
          ),
          FieldModel(
            label: "Country",
            hint: "Select a country",
            dataType: FieldDataType.dropdown,
            value: null,
            validations: {"required": true},
            options: [
              "United States",
              "Canada",
              "United Kingdom",
              "Australia",
              "Germany",
              "France",
              "Other"
            ],
            allowMultiple: false,
            isPermanent: true,
          ),
        ],
      ),
      SectionModel(
        title: "Contact",
        order: 3,
        isPermanent: true,
        icon: Icons.contact_page,
        fields: [
          FieldModel(
            label: "Email",
            hint: "Enter email address",
            dataType: FieldDataType.number,
            value: null,
            validations: {"required": true, "email": true},
            options: null,
            allowMultiple: false,
            isPermanent: true,
          ),
          FieldModel(
            label: "Phone",
            hint: "+1 234 567 890",
            dataType: FieldDataType.number,
            value: null,
            validations: {"required": true, "phone": true},
            options: null,
            allowMultiple: false,
            isPermanent: true,
          ),
          FieldModel(
            label: "Office Phone",
            hint: "+1 555 123 456",
            dataType: FieldDataType.number,
            value: null,
            validations: {},
            options: null,
            allowMultiple: false,
            isPermanent: false,
          ),
          FieldModel(
            label: "Emergency contact name",
            hint: "Jane Doe",
            dataType: FieldDataType.text,
            value: null,
            validations: {"required": true},
            options: null,
            allowMultiple: false,
            isPermanent: true,
          ),
          FieldModel(
            label: "Emergency contact phone",
            hint: "+1 987 654 321",
            dataType: FieldDataType.number,
            value: null,
            validations: {"required": true, "phone": true},
            options: null,
            allowMultiple: false,
            isPermanent: true,
          ),
          FieldModel(
            label: "LinkedIn",
            hint: "https://linkedin.com/in/username",
            dataType: FieldDataType.text,
            value: null,
            validations: {},
            options: null,
            allowMultiple: false,
            isPermanent: false,
          ),
          FieldModel(
            label: "Facebook",
            hint: "https://facebook.com/username",
            dataType: FieldDataType.text,
            value: null,
            validations: {},
            options: null,
            allowMultiple: false,
            isPermanent: false,
          ),
          FieldModel(
            label: "Twitter",
            hint: "https://twitter.com/username",
            dataType: FieldDataType.text,
            value: null,
            validations: {},
            options: null,
            allowMultiple: false,
            isPermanent: false,
          ),
          FieldModel(
            label: "Instagram",
            hint: "https://instagram.com/username",
            dataType: FieldDataType.text,
            value: null,
            validations: {},
            options: null,
            allowMultiple: false,
            isPermanent: false,
          ),
        ],
      ),
      SectionModel(
        title: "Education",
        order: 4,
        isPermanent: true,
        icon: Icons.school,
        subSections: [
          SubsectionModel(title: "", order: 1, fields: [
            FieldModel(
              label: "College/Institution",
              hint: "Harvard University",
              dataType: FieldDataType.text,
              value: null,
              validations: {"required": true},
              options: null,
              allowMultiple: false,
              isPermanent: true,
            ),
            FieldModel(
              label: "Major/Specialization",
              hint: "Computer Science",
              dataType: FieldDataType.text,
              value: null,
              validations: {"required": true},
              options: null,
              allowMultiple: false,
              isPermanent: true,
            ),
            FieldModel(
              label: "Degree",
              hint: "Select degree",
              dataType: FieldDataType.dropdown,
              value: null,
              validations: {"required": true},
              options: [
                "High School",
                "Associate's",
                "Bachelor's",
                "Master's",
                "Doctorate",
                "Other"
              ],
              allowMultiple: false,
              isPermanent: true,
            ),
            FieldModel(
              label: "GPA",
              hint: "3.8",
              dataType: FieldDataType.number,
              value: null,
              validations: {},
              options: null,
              allowMultiple: false,
              isPermanent: false,
            ),
            FieldModel(
              label: "Start date",
              hint: "mm/dd/yyyy",
              dataType: FieldDataType.date,
              value: null,
              validations: {"required": true},
              options: null,
              allowMultiple: false,
              isPermanent: true,
            ),
            FieldModel(
              label: "End date",
              hint: "mm/dd/yyyy",
              dataType: FieldDataType.date,
              value: null,
              validations: {},
              options: null,
              allowMultiple: false,
              isPermanent: false,
            ),
            FieldModel(
              label: "Currently studying",
              hint: "",
              dataType: FieldDataType.checkbox,
              value: null,
              validations: {},
              options: null,
              allowMultiple: false,
              isPermanent: false,
            ),
          ])
        ],
        fields: [
          FieldModel(
            label: " AddEducation",
            hint: "Harvard University",
            dataType: FieldDataType.text,
            value: null,
            validations: {"required": true},
            options: null,
            allowMultiple: false,
            isPermanent: true,
          ),
        ],
      ),
      SectionModel(
        title: "Visa",
        order: 5,
        isPermanent: true,
        icon: Icons.assignment,
        fields: [
          FieldModel(
            label: "Visa Type",
            hint: "Select visa type",
            dataType: FieldDataType.dropdown,
            value: null,
            validations: {},
            options: [
              "Work Visa",
              "Student Visa",
              "Tourist Visa",
              "Permanent Resident",
              "Other"
            ],
            allowMultiple: false,
            isPermanent: false,
          ),
          FieldModel(
            label: "Issuing Country",
            hint: "Enter issuing country",
            dataType: FieldDataType.text,
            value: null,
            validations: {},
            options: null,
            allowMultiple: false,
            isPermanent: false,
          ),
          FieldModel(
            label: "Issued Date",
            hint: "mm/dd/yyyy",
            dataType: FieldDataType.date,
            value: null,
            validations: {},
            options: null,
            allowMultiple: false,
            isPermanent: false,
          ),
          FieldModel(
            label: "Expiration Date",
            hint: "mm/dd/yyyy",
            dataType: FieldDataType.date,
            value: null,
            validations: {},
            options: null,
            allowMultiple: false,
            isPermanent: false,
          ),
          FieldModel(
            label: "Status",
            hint: "Select status",
            dataType: FieldDataType.dropdown,
            value: null,
            validations: {},
            options: ["Active", "Expired", "Pending", "Revoked"],
            allowMultiple: false,
            isPermanent: false,
          ),
          FieldModel(
            label: "Note",
            hint: "Add any notes",
            dataType: FieldDataType.text,
            value: null,
            validations: {},
            options: null,
            allowMultiple: false,
            isPermanent: false,
          ),
        ],
      ),
    ],
  ),
  TabModel(
    title: "Job",
    order: 2,
    isPermanent: true,
    tabType: TabType.form,
    icon: Icons.work,
    sections: [
      // Employment Section
      SectionModel(
        title: "Employment",
        order: 1,
        isPermanent: true,
        icon: Icons.badge,
        fields: [
          FieldModel(
            label: "Hire Date",
            hint: "mm/dd/yyyy",
            dataType: FieldDataType.date,
            value: null,
            validations: {"required": true},
            options: null,
            allowMultiple: false,
            isPermanent: true,
          ),
          FieldModel(
            label: "EEO Job Category",
            hint: "Select EEO category",
            dataType: FieldDataType.dropdown,
            value: null,
            validations: {},
            options: [
              "Executive/Senior Level Officials and Managers",
              "First/Mid-Level Officials and Managers",
              "Professionals",
              "Technicians",
              "Sales Workers",
              "Administrative Support Workers",
              "Craft Workers",
              "Operatives",
              "Laborers and Helpers",
              "Service Workers"
            ],
            allowMultiple: false,
            isPermanent: false,
          ),
          FieldModel(
            label: "Veteran Status",
            hint: "Select veteran status",
            dataType: FieldDataType.checkbox,
            value: null,
            validations: {},
            options: [
              "Active Duty Wartime or Campaign Badge Veteran",
              "Disabled Veteran",
              "Armed Forces Service Medal Veteran",
              "Recently Separated Veteran"
            ],
            allowMultiple: true,
            isPermanent: false,
          ),
        ],
      ),

      // Employment Status Section
      SectionModel(
        title: "Employment Status",
        order: 2,
        isPermanent: true,
        icon: Icons.assignment_ind,
        fields: [
          FieldModel(
            label: "Effective Date",
            hint: "mm/dd/yyyy",
            dataType: FieldDataType.date,
            value: null,
            validations: {"required": true},
            options: null,
            allowMultiple: false,
            isPermanent: true,
          ),
          FieldModel(
            label: "Status",
            hint: "Select employment status",
            dataType: FieldDataType.dropdown,
            value: null,
            validations: {"required": true},
            options: [
              "Active",
              "On Leave",
              "Suspended",
              "Terminated",
              "Retired"
            ],
            allowMultiple: false,
            isPermanent: true,
          ),
          FieldModel(
            label: "Comment",
            hint: "Add comment about status change",
            dataType: FieldDataType.text,
            value: null,
            validations: {},
            options: null,
            allowMultiple: false,
            isPermanent: false,
          ),
        ],
      ),

      // Job Information Section
      SectionModel(
        title: "Job Information",
        order: 3,
        isPermanent: true,
        icon: Icons.work_outline,
        fields: [
          FieldModel(
            label: "Effective Date",
            hint: "mm/dd/yyyy",
            dataType: FieldDataType.date,
            value: null,
            validations: {"required": true},
            options: null,
            allowMultiple: false,
            isPermanent: true,
          ),
          FieldModel(
            label: "Location",
            hint: "Enter work location",
            dataType: FieldDataType.text,
            value: null,
            validations: {"required": true},
            options: null,
            allowMultiple: false,
            isPermanent: true,
          ),
          FieldModel(
            label: "Division",
            hint: "Enter division",
            dataType: FieldDataType.text,
            value: null,
            validations: {},
            options: null,
            allowMultiple: false,
            isPermanent: false,
          ),
          FieldModel(
            label: "Department",
            hint: "Enter department",
            dataType: FieldDataType.text,
            value: null,
            validations: {"required": true},
            options: null,
            allowMultiple: false,
            isPermanent: true,
          ),
          FieldModel(
            label: "Teams",
            hint: "Enter team names",
            dataType: FieldDataType.text,
            value: null,
            validations: {},
            options: null,
            allowMultiple: true,
            isPermanent: false,
          ),
          FieldModel(
            label: "Job Title",
            hint: "Enter job title",
            dataType: FieldDataType.text,
            value: null,
            validations: {"required": true},
            options: null,
            allowMultiple: false,
            isPermanent: true,
          ),
          FieldModel(
            label: "Reports To",
            hint: "Select supervisor",
            dataType: FieldDataType.dropdown,
            value: null,
            validations: {"required": true},
            options: [
              "Maja Andev",
              "Eric Asture",
              "Cheryl Barnet",
              "Jake Bryan",
              "Jennifer Caldwell",
              "Dorothy Chou",
              "Ryota Saito",
              "Jeremy Steel",
              "Daniel Vance",
              "Trent Walsh"
            ],
            allowMultiple: false,
            isPermanent: true,
          ),
        ],
      ),

      // Compensation Section
      SectionModel(
        title: "Compensation",
        order: 4,
        isPermanent: true,
        icon: Icons.attach_money,
        fields: [
          FieldModel(
            label: "Effective Date",
            hint: "mm/dd/yyyy",
            dataType: FieldDataType.date,
            value: null,
            validations: {"required": true},
            options: null,
            allowMultiple: false,
            isPermanent: true,
          ),
          FieldModel(
            label: "Schedule",
            hint: "Select pay schedule",
            dataType: FieldDataType.dropdown,
            value: null,
            validations: {"required": true},
            options: [
              "Weekly",
              "Bi-weekly",
              "Semi-monthly",
              "Monthly",
              "Annual"
            ],
            allowMultiple: false,
            isPermanent: true,
          ),
          FieldModel(
            label: "Type",
            hint: "Select compensation type",
            dataType: FieldDataType.dropdown,
            value: null,
            validations: {"required": true},
            options: ["Salary", "Hourly", "Commission", "Bonus", "Equity"],
            allowMultiple: false,
            isPermanent: true,
          ),
          FieldModel(
            label: "Rate",
            hint: "Enter rate/amount",
            dataType: FieldDataType.number,
            value: null,
            validations: {"required": true},
            options: null,
            allowMultiple: false,
            isPermanent: true,
          ),
          FieldModel(
            label: "OT Eligible",
            hint: "Overtime eligibility",
            dataType: FieldDataType.checkbox,
            value: null,
            validations: {},
            options: null,
            allowMultiple: false,
            isPermanent: false,
          ),
          FieldModel(
            label: "Reason",
            hint: "Reason for compensation change",
            dataType: FieldDataType.text,
            value: null,
            validations: {},
            options: null,
            allowMultiple: false,
            isPermanent: false,
          ),
          FieldModel(
            label: "Comment",
            hint: "Additional comments",
            dataType: FieldDataType.text,
            value: null,
            validations: {},
            options: null,
            allowMultiple: false,
            isPermanent: false,
          ),
        ],
      ),

      // Potential Bonus Section
      SectionModel(
        title: "Potential Bonus",
        order: 5,
        isPermanent: true,
        icon: Icons.trending_up,
        fields: [
          FieldModel(
            label: "Annual Percentage",
            hint: "10%",
            dataType: FieldDataType.number,
            value: null,
            validations: {},
            options: null,
            allowMultiple: false,
            isPermanent: false,
          ),
          FieldModel(
            label: "Annual Amount",
            hint: "0.00",
            dataType: FieldDataType.number,
            value: null,
            validations: {},
            options: null,
            allowMultiple: false,
            isPermanent: false,
          ),
          FieldModel(
            label: "Currency",
            hint: "Select currency",
            dataType: FieldDataType.dropdown,
            value: null,
            validations: {},
            options: ["USD", "EUR", "GBP", "PKR", "INR", "JPY", "CAD"],
            allowMultiple: false,
            isPermanent: false,
          ),
        ],
      ),

      // Bonus Section
      SectionModel(
        title: "Bonus",
        order: 6,
        isPermanent: true,
        icon: Icons.card_giftcard,
        fields: [
          FieldModel(
            label: "Date",
            hint: "mm/dd/yyyy",
            dataType: FieldDataType.date,
            value: null,
            validations: {"required": true},
            options: null,
            allowMultiple: false,
            isPermanent: true,
          ),
          FieldModel(
            label: "Amount",
            hint: "Enter bonus amount",
            dataType: FieldDataType.number,
            value: null,
            validations: {"required": true},
            options: null,
            allowMultiple: false,
            isPermanent: true,
          ),
          FieldModel(
            label: "Reason",
            hint: "Reason for bonus",
            dataType: FieldDataType.text,
            value: null,
            validations: {},
            options: null,
            allowMultiple: false,
            isPermanent: false,
          ),
          FieldModel(
            label: "Comment",
            hint: "Additional comments",
            dataType: FieldDataType.text,
            value: null,
            validations: {},
            options: null,
            allowMultiple: false,
            isPermanent: false,
          ),
        ],
      ),

      // Commission Section
      SectionModel(
        title: "Commission",
        order: 7,
        isPermanent: true,
        icon: Icons.bar_chart,
        fields: [
          FieldModel(
            label: "Date",
            hint: "mm/dd/yyyy",
            dataType: FieldDataType.date,
            value: null,
            validations: {"required": true},
            options: null,
            allowMultiple: false,
            isPermanent: true,
          ),
          FieldModel(
            label: "Amount",
            hint: "Enter commission amount",
            dataType: FieldDataType.number,
            value: null,
            validations: {"required": true},
            options: null,
            allowMultiple: false,
            isPermanent: true,
          ),
          FieldModel(
            label: "Comment",
            hint: "Additional comments",
            dataType: FieldDataType.text,
            value: null,
            validations: {},
            options: null,
            allowMultiple: false,
            isPermanent: false,
          ),
        ],
      ),

      // Equity Section
      SectionModel(
        title: "Equity",
        order: 8,
        isPermanent: true,
        icon: Icons.pie_chart,
        fields: [
          FieldModel(
            label: "Type",
            hint: "Select equity type",
            dataType: FieldDataType.dropdown,
            value: null,
            validations: {},
            options: [
              "Stock Options",
              "Restricted Stock Units (RSUs)",
              "Performance Shares",
              "Stock Appreciation Rights (SARs)",
              "Phantom Stock",
              "Other"
            ],
            allowMultiple: false,
            isPermanent: false,
          ),
          FieldModel(
            label: "Custom Type",
            hint: "Enter custom type if other",
            dataType: FieldDataType.text,
            value: null,
            validations: {},
            options: null,
            allowMultiple: false,
            isPermanent: false,
          ),
          FieldModel(
            label: "Grant Date",
            hint: "mm/dd/yyyy",
            dataType: FieldDataType.date,
            value: null,
            validations: {},
            options: null,
            allowMultiple: false,
            isPermanent: false,
          ),
          FieldModel(
            label: "Vesting Start",
            hint: "mm/dd/yyyy",
            dataType: FieldDataType.date,
            value: null,
            validations: {},
            options: null,
            allowMultiple: false,
            isPermanent: false,
          ),
          FieldModel(
            label: "Granted",
            hint: "Number of shares/units granted",
            dataType: FieldDataType.number,
            value: null,
            validations: {},
            options: null,
            allowMultiple: false,
            isPermanent: false,
          ),
          FieldModel(
            label: "Strike Price",
            hint: "Enter strike price if applicable",
            dataType: FieldDataType.number,
            value: null,
            validations: {},
            options: null,
            allowMultiple: false,
            isPermanent: false,
          ),
          FieldModel(
            label: "Schedule",
            hint: "Vesting schedule",
            dataType: FieldDataType.text,
            value: null,
            validations: {},
            options: null,
            allowMultiple: false,
            isPermanent: false,
          ),
          FieldModel(
            label: "Months",
            hint: "Vesting period in months",
            dataType: FieldDataType.number,
            value: null,
            validations: {},
            options: null,
            allowMultiple: false,
            isPermanent: false,
          ),
          FieldModel(
            label: "Gift",
            hint: "Is this a gift?",
            dataType: FieldDataType.checkbox,
            value: null,
            validations: {},
            options: null,
            allowMultiple: false,
            isPermanent: false,
          ),
        ],
      ),

      // Direct Reports Section
      SectionModel(
        title: "Direct Reports",
        order: 9,
        isPermanent: true,
        icon: Icons.group,
        fields: [
          FieldModel(
            label: "Direct Reports",
            hint: "Select direct reports",
            dataType: FieldDataType.dropdown,
            value: null,
            validations: {},
            options: [
              "Maja Andev",
              "Eric Asture",
              "Cheryl Barnet",
              "Jake Bryan",
              "Jennifer Caldwell",
              "Dorothy Chou",
              "Ryota Saito",
              "Jeremy Steel",
              "Daniel Vance",
              "Trent Walsh"
            ],
            allowMultiple: true,
            isPermanent: false,
          ),
        ],
      ),
    ],
  ),
  TabModel(
    title: "Training",
    order: 3,
    isPermanent: true,
    tabType: TabType.form,
    icon: Icons.school,
    sections: [
      SectionModel(
        title: "Completed Trainings",
        order: 1,
        isPermanent: true,
        icon: Icons.check_circle,
        tables: [
          TableModel(
            title: "Training History",
            rowLabel: "Add Training",
            columns: ["Training Name", "Completion Date", "Certificate"],
            rows: [],
            isPermanent: true,
          ),
        ],
      ),
      SectionModel(
        title: "Required Trainings",
        order: 2,
        isPermanent: true,
        icon: Icons.assignment,
        fields: [
          FieldModel(
            label: "Safety Training",
            hint: "Select completion status",
            dataType: FieldDataType.dropdown,
            value: null,
            validations: {"required": true},
            options: ["Not Started", "In Progress", "Completed"],
            allowMultiple: false,
            isPermanent: true,
          ),
          FieldModel(
            label: "Compliance Training",
            hint: "Select completion status",
            dataType: FieldDataType.dropdown,
            value: null,
            validations: {"required": true},
            options: ["Not Started", "In Progress", "Completed"],
            allowMultiple: false,
            isPermanent: true,
          ),
        ],
      ),
    ],
  ),
  TabModel(
    title: "Time Off",
    order: 4,
    isPermanent: true,
    tabType: TabType.form,
    icon: Icons.beach_access,
    sections: [
      SectionModel(
        title: "Balance",
        order: 1,
        isPermanent: true,
        icon: Icons.account_balance_wallet,
        fields: [
          FieldModel(
            label: "Vacation Days",
            hint: "Remaining vacation days",
            dataType: FieldDataType.number,
            value: null,
            validations: {"readOnly": true},
            options: null,
            allowMultiple: false,
            isPermanent: true,
          ),
          FieldModel(
            label: "Sick Days",
            hint: "Remaining sick days",
            dataType: FieldDataType.number,
            value: null,
            validations: {"readOnly": true},
            options: null,
            allowMultiple: false,
            isPermanent: true,
          ),
        ],
      ),
      SectionModel(
        title: "Request Time Off",
        order: 2,
        isPermanent: true,
        icon: Icons.event_available,
        fields: [
          FieldModel(
            label: "Start Date",
            hint: "Select start date",
            dataType: FieldDataType.date,
            value: null,
            validations: {"required": true},
            options: null,
            allowMultiple: false,
            isPermanent: true,
          ),
          FieldModel(
            label: "End Date",
            hint: "Select end date",
            dataType: FieldDataType.date,
            value: null,
            validations: {"required": true},
            options: null,
            allowMultiple: false,
            isPermanent: true,
          ),
          FieldModel(
            label: "Type",
            hint: "Select time off type",
            dataType: FieldDataType.dropdown,
            value: null,
            validations: {"required": true},
            options: ["Vacation", "Sick Leave", "Personal Day", "Other"],
            allowMultiple: false,
            isPermanent: true,
          ),
        ],
      ),
    ],
  ),
  TabModel(
    title: "Documents",
    order: 5,
    isPermanent: true,
    tabType: TabType.documents,
    icon: Icons.folder,
    documents: [
      DocumentItem(
        name: "Employment Documents",
        type: DocumentType.folder,
        isPermanent: true,
        children: [
          DocumentItem(
            name: "Contract.pdf",
            type: DocumentType.file,
            isPermanent: true,
            fileUrl: "/documents/contract.pdf",
          ),
          DocumentItem(
            name: "Offer Letter.pdf",
            type: DocumentType.file,
            isPermanent: true,
            fileUrl: "/documents/offer_letter.pdf",
          ),
        ],
      ),
      DocumentItem(
        name: "ID Documents",
        type: DocumentType.folder,
        isPermanent: true,
        children: [
          DocumentItem(
            name: "Passport.pdf",
            type: DocumentType.file,
            isPermanent: true,
            fileUrl: "/documents/passport.pdf",
          ),
          DocumentItem(
            name: "Driver License.pdf",
            type: DocumentType.file,
            isPermanent: true,
            fileUrl: "/documents/license.pdf",
          ),
        ],
      ),
    ],
  ),
  TabModel(
    title: "Benefits",
    order: 6,
    isPermanent: true,
    tabType: TabType.form,
    icon: Icons.health_and_safety,
    sections: [
      SectionModel(
        title: "Health Insurance",
        order: 1,
        isPermanent: true,
        icon: Icons.local_hospital,
        fields: [
          FieldModel(
            label: "Plan Type",
            hint: "Select your health plan",
            dataType: FieldDataType.dropdown,
            value: null,
            validations: {"required": true},
            options: ["Basic", "Premium", "Family", "None"],
            allowMultiple: false,
            isPermanent: true,
          ),
          FieldModel(
            label: "Dependents",
            hint: "Number of dependents covered",
            dataType: FieldDataType.number,
            value: null,
            validations: {"min": 0, "max": 10},
            options: null,
            allowMultiple: false,
            isPermanent: true,
          ),
        ],
      ),
      SectionModel(
        title: "Retirement",
        order: 2,
        isPermanent: true,
        icon: Icons.account_balance,
        fields: [
          FieldModel(
            label: "401(k) Enrollment",
            hint: "Select enrollment status",
            dataType: FieldDataType.dropdown,
            value: null,
            validations: {"required": true},
            options: ["Enrolled", "Not Enrolled", "Pending"],
            allowMultiple: false,
            isPermanent: true,
          ),
          FieldModel(
            label: "Contribution Percentage",
            hint: "Enter contribution percentage",
            dataType: FieldDataType.number,
            value: null,
            validations: {"min": 0, "max": 50},
            options: null,
            allowMultiple: false,
            isPermanent: true,
          ),
        ],
      ),
    ],
  ),
  TabModel(
    title: "Notes",
    order: 7,
    isPermanent: true,
    tabType: TabType.notes,
    icon: Icons.note,
    notes: [
      NoteModel(
        text:
            "Initial onboarding completed successfully. All documents verified.",
        dateTime: DateTime(2023, 05, 15, 10, 30, 00),
        isPermanent: true,
      ),
      NoteModel(
        text: "Performance review scheduled for next quarter.",
        dateTime: DateTime(20, 06, 2023, 14, 45, 00),
        isPermanent: true,
      ),
    ],
  ),
  TabModel(
    title: "Assets",
    order: 8,
    isPermanent: true,
    tabType: TabType.form,
    icon: Icons.devices,
    sections: [
      SectionModel(
        title: "Assigned Equipment",
        order: 1,
        isPermanent: true,
        icon: Icons.computer,
        tables: [
          TableModel(
            title: "Company Assets",
            rowLabel: "Add Asset",
            columns: ["Asset Type", "Serial Number", "Assignment Date"],
            rows: [],
            isPermanent: true,
          ),
        ],
      ),
    ],
  ),
  TabModel(
    title: "Emergency",
    order: 9,
    isPermanent: true,
    tabType: TabType.form,
    icon: Icons.emergency,
    sections: [
      SectionModel(
        title: "Emergency Contacts",
        order: 1,
        isPermanent: true,
        icon: Icons.contact_emergency,
        tables: [
          TableModel(
            title: "Contacts",
            rowLabel: "Add Contact",
            columns: [
              "Name",
              "Relationship",
              "Phone Number",
              "Primary Contact"
            ],
            rows: [],
            isPermanent: true,
          ),
        ],
      ),
      SectionModel(
        title: "Medical Information",
        order: 2,
        isPermanent: true,
        icon: Icons.medical_services,
        fields: [
          FieldModel(
            label: "Blood Type",
            hint: "Select your blood type",
            dataType: FieldDataType.dropdown,
            value: null,
            validations: {},
            options: [
              "A+",
              "A-",
              "B+",
              "B-",
              "AB+",
              "AB-",
              "O+",
              "O-",
              "Unknown"
            ],
            allowMultiple: false,
            isPermanent: true,
          ),
          FieldModel(
            label: "Allergies",
            hint: "List any allergies",
            dataType: FieldDataType.text,
            value: null,
            validations: {},
            options: null,
            allowMultiple: false,
            isPermanent: true,
          ),
        ],
      ),
    ],
  ),
  TabModel(
    title: "Covid-19",
    order: 10,
    isPermanent: true,
    tabType: TabType.form,
    icon: Icons.coronavirus,
    sections: [
      SectionModel(
        title: "Vaccination Status",
        order: 1,
        isPermanent: true,
        icon: Icons.vaccines,
        fields: [
          FieldModel(
            label: "Vaccination Status",
            hint: "Select your vaccination status",
            dataType: FieldDataType.dropdown,
            value: null,
            validations: {"required": true},
            options: [
              "Not Vaccinated",
              "Partially Vaccinated",
              "Fully Vaccinated",
              "Booster Received"
            ],
            allowMultiple: false,
            isPermanent: true,
          ),
          FieldModel(
            label: "Last Vaccine Date",
            hint: "Select date of last vaccine",
            dataType: FieldDataType.date,
            value: null,
            validations: {},
            options: null,
            allowMultiple: false,
            isPermanent: true,
          ),
        ],
      ),
      SectionModel(
        title: "Test Results",
        order: 2,
        isPermanent: true,
        icon: Icons.assignment_returned,
        tables: [
          TableModel(
            title: "Covid Test History",
            rowLabel: "Add Test Result",
            columns: ["Test Date", "Test Type", "Result"],
            rows: [],
            isPermanent: true,
          ),
        ],
      ),
    ],
  ),
  TabModel(
    title: "OnBoarding",
    order: 11,
    isPermanent: true,
    tabType: TabType.form,
    icon: Icons.person_add,
    sections: [
      SectionModel(
        title: "Checklist",
        order: 1,
        isPermanent: true,
        icon: Icons.checklist,
        fields: [
          FieldModel(
            label: "Paperwork Completed",
            hint: "Check if completed",
            dataType: FieldDataType.checkbox,
            value: null,
            validations: {},
            options: ["Completed"],
            allowMultiple: false,
            isPermanent: true,
          ),
          FieldModel(
            label: "Equipment Assigned",
            hint: "Check if completed",
            dataType: FieldDataType.checkbox,
            value: null,
            validations: {},
            options: ["Completed"],
            allowMultiple: false,
            isPermanent: true,
          ),
          FieldModel(
            label: "Orientation Completed",
            hint: "Check if completed",
            dataType: FieldDataType.checkbox,
            value: null,
            validations: {},
            options: ["Completed"],
            allowMultiple: false,
            isPermanent: true,
          ),
        ],
      ),
    ],
  ),
  TabModel(
    title: "OffBoarding",
    order: 12,
    isPermanent: true,
    tabType: TabType.form,
    icon: Icons.person_remove,
    sections: [
      SectionModel(
        title: "Exit Checklist",
        order: 1,
        isPermanent: true,
        icon: Icons.exit_to_app,
        fields: [
          FieldModel(
            label: "Equipment Returned",
            hint: "Check if completed",
            dataType: FieldDataType.checkbox,
            value: null,
            validations: {},
            options: ["Completed"],
            allowMultiple: false,
            isPermanent: true,
          ),
          FieldModel(
            label: "Access Revoked",
            hint: "Check if completed",
            dataType: FieldDataType.checkbox,
            value: null,
            validations: {},
            options: ["Completed"],
            allowMultiple: false,
            isPermanent: true,
          ),
          FieldModel(
            label: "Exit Interview Completed",
            hint: "Check if completed",
            dataType: FieldDataType.checkbox,
            value: null,
            validations: {},
            options: ["Completed"],
            allowMultiple: false,
            isPermanent: true,
          ),
        ],
      ),
      SectionModel(
        title: "Final Details",
        order: 2,
        isPermanent: true,
        icon: Icons.description,
        fields: [
          FieldModel(
            label: "Last Working Day",
            hint: "Select your last working day",
            dataType: FieldDataType.date,
            value: null,
            validations: {"required": true},
            options: null,
            allowMultiple: false,
            isPermanent: true,
          ),
          FieldModel(
            label: "Forwarding Address",
            hint: "Enter address for final documents",
            dataType: FieldDataType.text,
            value: null,
            validations: {},
            options: null,
            allowMultiple: false,
            isPermanent: true,
          ),
        ],
      ),
    ],
  ),
];
